name: Push_Docker TAG

on:
  schedule:
    - cron:  '39 8 * * 5'
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get the TAG
        run: echo "TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      -
        name: Push_Docker TAG
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            yanik39/torproxy:${{ env.TAG }}
            yanik39/torproxy:latest
            ghcr.io/yanik39/torproxy:${{ env.TAG }}
            ghcr.io/yanik39/torproxy-latest:latest
      -
        name: Git Checkout
        uses: actions/checkout@v2
      -
        name: Push_Docker Readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: yanik39/torproxy
