#!/bin/bash

pids=( $(pgrep curl) )
kill -9 ${pids[@]/#/-p } &>/dev/null

return1=0
return2=0

timeout 10s torsocks curl -s --http1.1 --max-time 9 "https://check.torproject.org/" | grep -qm1 Congratulations
return1=$?
if [[ $return1 == 0 ]]
then
	echo "[Pass: Tor Project Check]"
	timeout 10s torsocks curl -s -I --http1.1 --max-time 9 "http://5ekxbftvqg26oir5wle3p27ax3wksbxcecnm6oemju7bjra2pn26s3qd.onion" | grep -q 200
	return2=$?
	if [[ $return2 == 0 ]]
	then
		echo "[Pass: Debian Onion Address]"
	else
		echo "[Fail: Debian Onion Address]"
	fi
else
	echo "[Fail: Tor Project Check]"
	echo "[ *** Skipping Remaining Checks *** ]"
fi

return=$((return1+return2))
count=0

if [[ $return == 0 ]]
then
	echo 0 > /help/HealthCount
	exit 0
else
	count=$(cat /help/HealthCount)
	if [[ $count > 8 ]]
	then
		echo "Too Many Fails: Restarting TOR"
		/usr/local/bin/python3 /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf stop TOR
		sleep 5
		/usr/local/bin/python3 /usr/local/bin/supervisorctl -c /etc/supervisor/supervisord.conf start TOR
		pids=( $(pgrep curl) )
		kill -9 ${pids[@]/#/-p } &>/dev/null
		echo 0 > /help/HealthCount
	else
		echo $((count+1)) > /help/HealthCount
	fi
	exit 1
fi
